// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.9
// source: doingSSH.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SSHServerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerUsername string `protobuf:"bytes,1,opt,name=server_username,json=serverUsername,proto3" json:"server_username,omitempty"`
	ServerPassword string `protobuf:"bytes,2,opt,name=server_password,json=serverPassword,proto3" json:"server_password,omitempty"`
	ServerIp       string `protobuf:"bytes,3,opt,name=server_ip,json=serverIp,proto3" json:"server_ip,omitempty"`
	Command        string `protobuf:"bytes,4,opt,name=command,proto3" json:"command,omitempty"`
}

func (x *SSHServerRequest) Reset() {
	*x = SSHServerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_doingSSH_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SSHServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSHServerRequest) ProtoMessage() {}

func (x *SSHServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_doingSSH_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SSHServerRequest.ProtoReflect.Descriptor instead.
func (*SSHServerRequest) Descriptor() ([]byte, []int) {
	return file_doingSSH_proto_rawDescGZIP(), []int{0}
}

func (x *SSHServerRequest) GetServerUsername() string {
	if x != nil {
		return x.ServerUsername
	}
	return ""
}

func (x *SSHServerRequest) GetServerPassword() string {
	if x != nil {
		return x.ServerPassword
	}
	return ""
}

func (x *SSHServerRequest) GetServerIp() string {
	if x != nil {
		return x.ServerIp
	}
	return ""
}

func (x *SSHServerRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

type SSHServerSSHResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *SSHServerSSHResponse) Reset() {
	*x = SSHServerSSHResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_doingSSH_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SSHServerSSHResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSHServerSSHResponse) ProtoMessage() {}

func (x *SSHServerSSHResponse) ProtoReflect() protoreflect.Message {
	mi := &file_doingSSH_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SSHServerSSHResponse.ProtoReflect.Descriptor instead.
func (*SSHServerSSHResponse) Descriptor() ([]byte, []int) {
	return file_doingSSH_proto_rawDescGZIP(), []int{1}
}

func (x *SSHServerSSHResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_doingSSH_proto protoreflect.FileDescriptor

var file_doingSSH_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x64, 0x6f, 0x69, 0x6e, 0x67, 0x53, 0x53, 0x48, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x64, 0x6f, 0x69, 0x6e, 0x67, 0x53, 0x53, 0x48, 0x22, 0x9b, 0x01, 0x0a, 0x10, 0x53,
	0x53, 0x48, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x27, 0x0a, 0x0f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x5f, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x69, 0x70, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x70, 0x12, 0x18,
	0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x22, 0x2e, 0x0a, 0x14, 0x53, 0x53, 0x48, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x53, 0x48, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x32, 0x53, 0x0a, 0x08, 0x64, 0x6f, 0x69, 0x6e,
	0x67, 0x53, 0x53, 0x48, 0x12, 0x47, 0x0a, 0x09, 0x53, 0x53, 0x48, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x12, 0x1a, 0x2e, 0x64, 0x6f, 0x69, 0x6e, 0x67, 0x53, 0x53, 0x48, 0x2e, 0x53, 0x53, 0x48,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e,
	0x64, 0x6f, 0x69, 0x6e, 0x67, 0x53, 0x53, 0x48, 0x2e, 0x53, 0x53, 0x48, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x53, 0x53, 0x48, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x28, 0x5a,
	0x26, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x63, 0x68, 0x61,
	0x69, 0x6a, 0x6d, 0x2f, 0x67, 0x52, 0x50, 0x43, 0x2f, 0x64, 0x6f, 0x69, 0x6e, 0x67, 0x53, 0x53,
	0x48, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_doingSSH_proto_rawDescOnce sync.Once
	file_doingSSH_proto_rawDescData = file_doingSSH_proto_rawDesc
)

func file_doingSSH_proto_rawDescGZIP() []byte {
	file_doingSSH_proto_rawDescOnce.Do(func() {
		file_doingSSH_proto_rawDescData = protoimpl.X.CompressGZIP(file_doingSSH_proto_rawDescData)
	})
	return file_doingSSH_proto_rawDescData
}

var file_doingSSH_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_doingSSH_proto_goTypes = []interface{}{
	(*SSHServerRequest)(nil),     // 0: doingSSH.SSHServerRequest
	(*SSHServerSSHResponse)(nil), // 1: doingSSH.SSHServerSSHResponse
}
var file_doingSSH_proto_depIdxs = []int32{
	0, // 0: doingSSH.doingSSH.SSHServer:input_type -> doingSSH.SSHServerRequest
	1, // 1: doingSSH.doingSSH.SSHServer:output_type -> doingSSH.SSHServerSSHResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_doingSSH_proto_init() }
func file_doingSSH_proto_init() {
	if File_doingSSH_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_doingSSH_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SSHServerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_doingSSH_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SSHServerSSHResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_doingSSH_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_doingSSH_proto_goTypes,
		DependencyIndexes: file_doingSSH_proto_depIdxs,
		MessageInfos:      file_doingSSH_proto_msgTypes,
	}.Build()
	File_doingSSH_proto = out.File
	file_doingSSH_proto_rawDesc = nil
	file_doingSSH_proto_goTypes = nil
	file_doingSSH_proto_depIdxs = nil
}
