// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.9
// source: doingSSH.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DoingSSHClient is the client API for DoingSSH service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DoingSSHClient interface {
	SSHServer(ctx context.Context, in *SSHServerRequest, opts ...grpc.CallOption) (*SSHServerSSHResponse, error)
}

type doingSSHClient struct {
	cc grpc.ClientConnInterface
}

func NewDoingSSHClient(cc grpc.ClientConnInterface) DoingSSHClient {
	return &doingSSHClient{cc}
}

func (c *doingSSHClient) SSHServer(ctx context.Context, in *SSHServerRequest, opts ...grpc.CallOption) (*SSHServerSSHResponse, error) {
	out := new(SSHServerSSHResponse)
	err := c.cc.Invoke(ctx, "/doingSSH.doingSSH/SSHServer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DoingSSHServer is the server API for DoingSSH service.
// All implementations must embed UnimplementedDoingSSHServer
// for forward compatibility
type DoingSSHServer interface {
	SSHServer(context.Context, *SSHServerRequest) (*SSHServerSSHResponse, error)
	mustEmbedUnimplementedDoingSSHServer()
}

// UnimplementedDoingSSHServer must be embedded to have forward compatible implementations.
type UnimplementedDoingSSHServer struct {
}

func (UnimplementedDoingSSHServer) SSHServer(context.Context, *SSHServerRequest) (*SSHServerSSHResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SSHServer not implemented")
}
func (UnimplementedDoingSSHServer) mustEmbedUnimplementedDoingSSHServer() {}

// UnsafeDoingSSHServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DoingSSHServer will
// result in compilation errors.
type UnsafeDoingSSHServer interface {
	mustEmbedUnimplementedDoingSSHServer()
}

func RegisterDoingSSHServer(s grpc.ServiceRegistrar, srv DoingSSHServer) {
	s.RegisterService(&DoingSSH_ServiceDesc, srv)
}

func _DoingSSH_SSHServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SSHServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DoingSSHServer).SSHServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/doingSSH.doingSSH/SSHServer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DoingSSHServer).SSHServer(ctx, req.(*SSHServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DoingSSH_ServiceDesc is the grpc.ServiceDesc for DoingSSH service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DoingSSH_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "doingSSH.doingSSH",
	HandlerType: (*DoingSSHServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SSHServer",
			Handler:    _DoingSSH_SSHServer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "doingSSH.proto",
}
